// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonsterHunterDB.Data;

#nullable disable

namespace MonsterHunterDB.Migrations
{
    [DbContext(typeof(MonsterDataContext))]
    [Migration("20231114150017_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("MonsterHunterDB.Data.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MonsterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Monsters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
                            FirstName = "Ortensia",
                            LastName = "Daniellot",
                            MonsterName = "methodology",
                            Type = "Marketing"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.",
                            FirstName = "Barbi",
                            LastName = "Leinster",
                            MonsterName = "service-desk",
                            Type = "Sales"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Vivamus tortor. Duis mattis egestas metus.",
                            FirstName = "Chloe",
                            LastName = "Ucceli",
                            MonsterName = "mobile",
                            Type = "Accounting"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Aenean lectus.",
                            FirstName = "Reggie",
                            LastName = "Catterell",
                            MonsterName = "Open-source",
                            Type = "Accounting"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.",
                            FirstName = "Ramsay",
                            LastName = "Beamand",
                            MonsterName = "exuding",
                            Type = "Product Management"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Vestibulum ante ipsum primis  faucibus orci luctus et ultrices posuere cubilia Curae; Donec.",
                            FirstName = "Jorie",
                            LastName = "Haulkham",
                            MonsterName = "mobile",
                            Type = "Human Resources"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Quisque erat eros",
                            FirstName = "Alejoa",
                            LastName = "Ord",
                            MonsterName = "Quality-focused",
                            Type = "Research and Development"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Phasellus sit amet erat.",
                            FirstName = "Vasily",
                            LastName = "Celes",
                            MonsterName = "Multi-lateral",
                            Type = "Support"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Aliquam augue quam",
                            FirstName = "Marcille",
                            LastName = "Messingham",
                            MonsterName = "task-force",
                            Type = "Human Resources"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Aliquam non mauris. Morbi non lectus.",
                            FirstName = "Kellia",
                            LastName = "Crimes",
                            MonsterName = "array",
                            Type = "Human Resources"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Cras pellentesque volutpat dui.",
                            FirstName = "Dyane",
                            LastName = "Close",
                            MonsterName = "Grass-roots",
                            Type = "Engineering"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Proin risus. Praesent lectus.",
                            FirstName = "Clarinda",
                            LastName = "Cowwell",
                            MonsterName = "solution",
                            Type = "Research and Development"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.",
                            FirstName = "Ginger",
                            LastName = "Isacoff",
                            MonsterName = "time-frame",
                            Type = "Human Resources"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Vestibulum ante ipsum primis  faucibus orci luctus et ultrices posuere cubilia Curae; Donec ",
                            FirstName = "Lita",
                            LastName = "Kinahan",
                            MonsterName = "toolset",
                            Type = "Human Resources"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
                            FirstName = "Fulton",
                            LastName = "Hartland",
                            MonsterName = "Implemented",
                            Type = "Support"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Cras pellentesque volutpat dui.Maecenas tristique",
                            FirstName = "Dev",
                            LastName = "Dietzler",
                            MonsterName = "multi-tasking",
                            Type = "Services"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Nam dui.",
                            FirstName = "Aubrie",
                            LastName = "Brandoni",
                            MonsterName = "executive",
                            Type = "Services"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Aliquam erat volutpat.",
                            FirstName = "Carlynne",
                            LastName = "Ruslen",
                            MonsterName = "bifurcated",
                            Type = "Support"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Nam dui.",
                            FirstName = "Zitella",
                            LastName = "Mudle",
                            MonsterName = "Robust",
                            Type = "Training"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Etiam faucibus cursus urna.",
                            FirstName = "Beatrisa",
                            LastName = "La Vigne",
                            MonsterName = "database",
                            Type = "Engineering"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Aliquam augue quam",
                            FirstName = "Phaedra",
                            LastName = "Huntingdon",
                            MonsterName = "policy",
                            Type = "Accounting"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Donec dapibus. Duis at velit eu est congue elementum.",
                            FirstName = "Vinni",
                            LastName = "Petrusch",
                            MonsterName = "motivating",
                            Type = "Training"
                        },
                        new
                        {
                            Id = 23,
                            Description = "In sagittis dui vel nisl. Duis ac nibh.",
                            FirstName = "Boy",
                            LastName = "Nolder",
                            MonsterName = "benchmark",
                            Type = "Human Resources"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Pellentesque eget nunc.",
                            FirstName = "Emlynn",
                            LastName = "Feathersby",
                            MonsterName = "Total",
                            Type = "Services"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Maecenas rhoncus aliquam lacus.",
                            FirstName = "Franz",
                            LastName = "Louys",
                            MonsterName = "website",
                            Type = "Marketing"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
